import SmartLink from '@/components/SmartLink'

const featuredSlugs = ['Science-Fair', 'science-camp', 'typical90-all-problems-zh']

export default function NotebookHome({ posts = [], githubRepos = [] }) {
  const featured = featuredSlugs.map(slug => posts.find(post => post.slug === slug || post.href?.endsWith(slug))).filter(Boolean)
  const projects = githubRepos.filter(repo => !repo.fork && repo.name !== 'BLOG').slice(0, 3)

  return <main className='w-full md:pr-8 pb-20'>
    <section className='notebook-card p-8 md:p-12 mb-14'>
      <div className='notebook-kicker mb-4'>Personal notebook · 2026</div>
      <h1 className='text-4xl md:text-6xl font-serif font-bold leading-tight mb-5'>寫下值得留下的筆記，<br />安排真正會發生的一週。</h1>
      <p className='text-lg text-gray-700 max-w-2xl leading-8'>這本筆記收藏我的專案與學習紀錄。寫給一個用鉛筆與墨水思考的開發者。</p>
      <div className='mt-8 flex flex-wrap gap-3'><SmartLink href='/archive' className='notebook-button'>翻閱文章</SmartLink><SmartLink href='/projects' className='notebook-button'>查看專案</SmartLink></div>
    </section>
    <section className='mb-14'><div className='notebook-kicker mb-3'>Hey there!</div><h2 className='text-3xl font-serif font-bold mb-4'>嗨，歡迎來到我的筆記本。</h2><p className='text-gray-700 leading-8 max-w-3xl'>泡杯咖啡，忽略散落的塗鴉，看看我正在做的專案、競程筆記與研究紀錄。</p></section>
    <section className='mb-16'><div className='notebook-kicker mb-2'>Coding activity</div><h2 className='text-3xl font-serif font-bold mb-6'>程式活動</h2><div className='grid lg:grid-cols-2 gap-6'><a href='https://github.com/benjamin-shih-tw' target='_blank' rel='noreferrer' className='notebook-card p-4'><img loading='lazy' className='w-full' alt='GitHub 個人統計' src='https://github-readme-stats.vercel.app/api?username=benjamin-shih-tw&show_icons=true&hide_border=true&bg_color=fffef9&title_color=9a7410&text_color=332d1f' /></a><a href='https://github.com/benjamin-shih-tw' target='_blank' rel='noreferrer' className='notebook-card p-4'><img loading='lazy' className='w-full' alt='GitHub 常用語言' src='https://github-readme-stats.vercel.app/api/top-langs/?username=benjamin-shih-tw&layout=compact&hide_border=true&bg_color=fffef9&title_color=9a7410&text_color=332d1f' /></a></div><div className='notebook-card p-4 mt-6 overflow-x-auto'><img loading='lazy' className='min-w-3xl w-full' alt='GitHub 提交熱度圖' src='https://ghchart.rshah.org/d5a719/benjamin-shih-tw' /></div><div className='grid md:grid-cols-2 gap-6 mt-6'><a href='https://codeforces.com/profile/benjaminshih2' target='_blank' rel='noreferrer' className='notebook-card p-6'><div className='notebook-kicker mb-2'>Codeforces</div><h3 className='text-xl font-bold'>@benjaminshih2 ↗</h3><p className='text-sm text-gray-600 mt-2'>查看即時 rating、解題與比賽紀錄。</p></a><a href='https://atcoder.jp/users/benjaminshih2' target='_blank' rel='noreferrer' className='notebook-card p-6'><div className='notebook-kicker mb-2'>AtCoder</div><h3 className='text-xl font-bold'>@benjaminshih2 ↗</h3><p className='text-sm text-gray-600 mt-2'>查看即時 rating、提交與比賽紀錄。</p></a></div></section>
    <section className='mb-16'><div className='flex justify-between items-end mb-6'><div><div className='notebook-kicker mb-2'>Selected notes</div><h2 className='text-3xl font-serif font-bold'>精選文章</h2></div><SmartLink href='/archive' className='text-sm underline'>全部文章 →</SmartLink></div><div className='grid md:grid-cols-3 gap-6'>{featured.map(post => <SmartLink key={post.id} href={post.href} className='notebook-card p-6 block hover:-translate-y-1 transition-transform'><div className='text-xs text-gray-500 mb-4'>{post.date?.start_date || post.publishDate}</div><h3 className='text-xl font-bold mb-3'>{post.title}</h3><p className='text-sm text-gray-600 leading-6'>{post.summary || '打開這頁筆記繼續閱讀。'}</p></SmartLink>)}</div></section>
    <section><div className='flex justify-between items-end mb-6'><div><div className='notebook-kicker mb-2'>Selected projects</div><h2 className='text-3xl font-serif font-bold'>精選專案</h2></div><SmartLink href='/projects' className='text-sm underline'>全部專案 →</SmartLink></div><div className='grid md:grid-cols-3 gap-6'>{projects.map(repo => <a key={repo.name} href={repo.html_url} target='_blank' rel='noreferrer' className='notebook-card p-6 block hover:-translate-y-1 transition-transform'><div className='text-2xl mb-3'>⌘</div><h3 className='text-lg font-bold mb-2'>{repo.name}</h3><p className='text-sm text-gray-600 leading-6 min-h-12'>{repo.description || 'GitHub 上的開發專案與實驗。'}</p><div className='mt-5 text-xs text-gray-500'>{repo.language || 'Code'} · 更新於 {repo.updated_at?.slice(0, 10)}</div></a>)}</div></section>
  </main>
}
